// export const CREATE_TUTORIAL = "CREATE_TUTORIAL";
export const RETRIEVE_JOURNEYS = "RETRIEVE_JOURNEYS";
// export const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
// export const DELETE_TUTORIAL = "DELETE_TUTORIAL";
// export const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";